@startuml Arquitetura

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN()

AddElementTag("project", $legendText="Vamos construir nesse vídeo", $fontColor="#ffffff", $bgColor="#08427B")

System(browser, "Browser", "Chrome, Firefox, Internet Explorer")

System_Boundary(c1, "Sistema para gestão pessoal") {
  Container(frontend, "Front-end", "React", "Interface onde o usuário realiza as operações")
  Container(api, "API", "Java, Spring Boot", "Uma API com as operações para gerenciar projetos, hábitos e métas", $tags="project")
  ContainerQueue(message_broker, "Message Broker", "Rabbit MQ", "", $tags="project")
  ContainerDb(database, "Database", "MySQL", "Banco de dados com as informações", $tags="project")
}

Rel(browser, frontend, "1. Carrega o front-end", "HTTPS")
Rel(browser, api, "2. Realiza as requisições", "HTTPS")

Rel(api, database, "4. Consulta", "TCP")
Rel(api, database, "3. Armazena", "TCP")

Rel(api, message_broker, "5. Publica eventos", "AMQP")

@enduml