@startuml Arquitetura

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LEFT_RIGHT()

AddElementTag("construir", $legendText="Vamos construir nesse vídeo", $fontColor="#ffffff", $bgColor="#08427B")

System(browser, "Browser", "Chrome, Firefox, Internet Explorer")

System_Boundary(c1, "Sistema para gestão de livros") {
  Container(frontend, "Front-end", "React", "Interface onde bibliotecário realiza as operações")
  Container(api, "API", "Java, Spring Boot", "Uma API com as operações para gerenciar os livros", $tags="construir")
  ContainerDb(database, "Database", "MySQL", "Banco de dados com as informações de autores e livros", $tags="construir")
}

Rel(browser, frontend, "1. Carrega o front-end", "HTTPS")
Rel(browser, api, "2. Realiza as requisições", "HTTPS")

Rel(api, database, "4. Consulta", "TCP")
Rel(api, database, "3. Armazena", "TCP")

@enduml