@startuml Caso de uso

left to right direction

actor "Usuário" as usuario

rectangle "Sistema para gestão pessoal" {
  usecase "Cadastrar um projeto" as A
  usecase "Cadastrar um hábito" as B
  usecase "Cadastrar uma meta" as C
}

usuario --> A
usuario --> B
usuario --> C

@enduml
